#define YY_CHAR char
#line 1 "/usr/local/lib/flexskel.cc"
/* A lexical scanner generated by flex */
/* scanner skeleton version:
 * $Header: /usr/fsys/odin/a/vern/flex/RCS/flex.skel,v 2.16 90/08/03 14:09:36 vern Exp $
 */
/* MODIFIED FOR C++ CLASS BY Alain Coetmeur: coetmeur(at)icdc.fr */
/* Note that (at) mean the 'at' symbol that I cannot write */
/* because it is expanded to the class name */
/* made at Informatique-CDC, Research&development department */
/* company from the Caisse Des Depots et Consignations */
/* institutional financial group  */

/* theses symbols are added before this file */
/* #define YY_CHAR 'unsigned char' if 8bit or 'char' if 7bit */
/* #define FLEX_DEBUG if debug mode */
#define FLEX_SCANNER
/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif
/* Old MSC, before c7 */
#ifdef MSDOS
#ifndef _MSDOS
#define _MSDOS
#endif
#endif
/* turboc */
#ifdef __MSDOS__
#ifndef _MSDOS
#define _MSDOS
#endif
#endif

#ifdef __cplusplus
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#ifndef YY_USE_CLASS
#define YY_USE_CLASS
#endif
#ifndef _MSDOS
#include <osfcn.h>
#endif
#else   /* ! __cplusplus */
#ifdef __STDC__
#ifdef __GNUC__
#include <stddef.h>
void *malloc( size_t );
void free( void* );
int read();
#else
#include <stdlib.h>
#endif  /* __GNUC__ */
#define YY_USE_PROTOS
#define YY_USE_CONST
#endif  /* __STDC__ */
#endif  /* ! __cplusplus */
#ifdef __TURBOC__
#define YY_USE_CONST
#endif
#include <stdio.h>


/*********************************************/
/* COMPILER DEPENDENT   MACROS               */
/*********************************************/
/* use prototypes in function declarations */
/* the "const" storage-class-modifier is valid */
#ifndef YY_USE_CONST
#define const
#endif
/* use prototypes in function declarations */
#ifndef YY_PROTO
#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif
#endif


/*********************/
/* parameters        */

/* amount of stuff to slurp up with each read */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif
/* size of default input buffer */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE (YY_READ_BUF_SIZE * 2) 
#endif

/***********************************/
/* to be redefined for application */

/* returned upon end-of-file */
#define YY_END_TOK 0
/* no semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#define yyterminate() return ( YY_NULL )

/* code executed at the end of each rule */
#define YY_BREAK break;

/* #define YY_USER_ACTION */
/* #define YY_USER_INIT */


#ifndef YY_USE_CLASS
/* copy whatever the last rule matched to the standard output */
/* cast to (char *) is because for 8-bit chars, yy___text is (unsigned char *) */
/* this used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite()
 */
#define ECHO (void) fwrite( (char *) yy___text, yy___leng, 1, yy___out )

/* gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifdef _MSDOS
#define YY_INPUT(buf,result,max_size) \
	if ( (result = fread(buf,1,max_size,yy___in)) < 0 ) \
	    YY_FATAL_ERROR( "fread() in flex scanner failed" );
#else
#define YY_INPUT(buf,result,max_size) \
	if ( (result = read( fileno(yy___in), (char *) buf, max_size )) < 0 ) \
	    YY_FATAL_ERROR( "read() in flex scanner failed" );

#endif
/* report a fatal error */

/* The funky do-while is used to turn this macro definition into
 * a single C statement (which needs a semi-colon terminator).
 * This avoids problems with code like:
 *
 *      if ( something_happens )
 *              YY_FATAL_ERROR( "oops, the something happened" );
 *      else
 *              everything_okay();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the YY_FATAL_ERROR() call.
 */

#define YY_FATAL_ERROR(msg) \
	do \
		{ \
		(void) fputs( msg, yy___stderr  ); \
		(void) putc( '\n', yy___stderr  ); \
		exit( 1 ); \
		} \
	while ( 0 )

/* default yywrap function - always treat EOF as an EOF */
#define yywrap() 1


/* default declaration of generated scanner - a define so the user can
 * easily add parameters
 */
#define YY_DECL int yylex YY_PROTO(( void )) 
#else 
/* c++ */
#define ECHO yy___echo()
#define YY_INPUT(buf,result,max_size) \
	if ( yy___input((char *)buf, result,max_size) < 0 ) \
	    YY_FATAL_ERROR( "YY_INPUT() in flex scanner failed" );

#define YY_FATAL_ERROR(msg) yy___fatal_error(msg)
#define yywrap() yy___wrap()

#endif
/***********************************/
/* not to be changed */
#define YY_NULL 0
#define YY_END_OF_BUFFER_CHAR 0
/* special action meaning "start processing a new file" */
#define YY_NEW_FILE yy___newfile 
/* enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN
 */
#define BEGIN yy_start = 1 + 2 *

/* action number for EOF rule of a given start state */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)



/* % section 1 definitions go here */ 
#line 1 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
#define INITIAL 0
/*
 * ShaderLex.l
 *
 * Copyright (C) 1995-96, Thomas Teuscher <teuscher@iam.unibe.ch>
 *                        University of Berne, Switzerland
 *
 * All rights reserved.
 *
 * This software may be freely copied, modified and redistributed
 * provided that this copyright note be preserved on all copies.
 * 
 * You may not distribute this software, in whole or in part, as part
 * of any commercial product without the express consent of the author.
 *
 * There is no warranty or other guarantee of fitness of this software
 * for any purpose. It is provided solely "as is".
 *
 * -----------------------------------------------------------------------------
 *  $Id: ShaderLex.l,v 1.4 1996/06/06 11:49:46 streit Exp $
 * -----------------------------------------------------------------------------
 */
#define YY_ShaderLex_FLEX_SCANNER
#define SKIP_REST_OF_LINE 1
#include "ShaderLex.h"
#line 49 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
#line 196 "/usr/local/lib/flexskel.cc"

#define yy___stderr YY_ShaderLex_ERRFILE
#define yy___text YY_ShaderLex_TEXT
#define yy___leng YY_ShaderLex_LENG
#define yy___in YY_ShaderLex_IN
#define yy___out YY_ShaderLex_OUT
#define yy___newfile \
	do \
		{ \
		YY_ShaderLex_INIT_BUFFER( YY_ShaderLex_CURRENT_BUFFER, yy___in ); \
		YY_ShaderLex_LOAD_BUFFER_STATE(); \
		} \
	while ( 0 )
#if YY_ShaderLex_DEBUG != 0
#define yy___flex_debug YY_ShaderLex_DEBUG_FLAG
#endif


#ifdef YY_USE_CLASS

#define yy___echo YY_ShaderLex_ECHO
#define yy___input YY_ShaderLex_INPUT
#define yy___fatal_error YY_ShaderLex_FATAL_ERROR
#define yy___wrap YY_ShaderLex_WRAP

#endif

/* done after the current pattern has been matched and before the
 * corresponding action - sets up yy___text
 */
#define YY_DO_BEFORE_ACTION \
	yy___text = yy_bp; \
/* % code to fiddle yy___text and yy___leng for yymore() goes here */ \
	yy___leng = yy_cp - yy_bp; \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* return all but the first 'n' matched characters back to the input stream */
#define yyless(n) \
	do \
		{ \
		/* undo effects of setting up yy___text */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n; \
		YY_DO_BEFORE_ACTION; /* set up yy___text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yy___text )



struct yy_buffer_state
    {
    YY_ShaderLex_IFILE  *yy_input_file;

    YY_ShaderLex_CHAR *yy_ch_buf;               /* input buffer */
    YY_ShaderLex_CHAR *yy_buf_pos;      /* current position in input buffer */

    /* size of input buffer in bytes, not including room for EOB characters */
    int yy_buf_size;    

    /* number of characters read into yy_ch_buf, not including EOB characters */
    int yy_n_chars;

    int yy_eof_status;          /* whether we've seen an EOF on this buffer */
#define EOF_NOT_SEEN 0
    /* "pending" happens when the EOF has been seen but there's still
     * some text process
     */
#define EOF_PENDING 1
#define EOF_DONE 2
    };

/* we provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state"
 */

#ifndef YY_USE_CLASS

#if YY_ShaderLex_DEBUG != 0
int YY_ShaderLex_DEBUG_FLAG=YY_ShaderLex_DEBUG_INIT;
#endif
#define YY_CURRENT_BUFFER YY_ShaderLex_CURRENT_BUFFER
static YY_BUFFER_STATE YY_ShaderLex_CURRENT_BUFFER;
/* yy_hold_char holds the character lost when yy___text is formed */
static YY_ShaderLex_CHAR yy_hold_char;

static int yy_n_chars;          /* number of characters read into yy_ch_buf */

/* GLOBAL */
YY_ShaderLex_CHAR *yy___text;
int yy___leng;

YY_ShaderLex_IFILE  *yy___in = (YY_ShaderLex_IFILE  *) 0;
YY_ShaderLex_OFILE *yy___out = (YY_ShaderLex_OFILE  *) 0;

#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
/* these variables are all declared out here so that section 3 code can
 * manipulate them
 */
/* points to current character in buffer */
static YY_ShaderLex_CHAR *yy_c_buf_p = (YY_ShaderLex_CHAR *) 0;
static int yy_init = 1;         /* whether we need to initialize */
static int yy_start = 0;        /* start state number */

/* flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yy___in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

static int yy_get_next_buffer YY_PROTO(( void ));
static void yyunput YY_PROTO(( YY_ShaderLex_CHAR c, YY_ShaderLex_CHAR *buf_ptr ));

#else
/* c++ */
#ifndef YY_ShaderLex_ECHO_NOCODE
void YY_ShaderLex_CLASS::yy___echo()
{YY_ShaderLex_ECHO_CODE
}
#endif
#ifndef YY_ShaderLex_INPUT_NOCODE
int  YY_ShaderLex_CLASS::yy___input(char * buffer,int &result,int max_size)
{YY_ShaderLex_INPUT_CODE
}
#endif
#ifndef YY_ShaderLex_FATAL_ERROR_NOCODE
void YY_ShaderLex_CLASS::yy___fatal_error(char *msg)
{YY_ShaderLex_FATAL_ERROR_CODE
}
#endif
#ifndef YY_ShaderLex_WRAP_NOCODE
int  YY_ShaderLex_CLASS::yy___wrap()
{YY_ShaderLex_WRAP_CODE
}
#endif
void YY_ShaderLex_CLASS::yy_initialize()
{
 yy___in=0;yy___out=0;yy_init = 1;
 yy_start=0;
 yy___text=0;yy___leng=0;
 YY_ShaderLex_CURRENT_BUFFER=0;
 yy_did_buffer_switch_on_eof=0;
 yy_c_buf_p=0;yy_hold_char=0;yy_n_chars=0;
#if YY_ShaderLex_DEBUG != 0
 YY_ShaderLex_DEBUG_FLAG=YY_ShaderLex_DEBUG_INIT;
#endif
}

YY_ShaderLex_CLASS::YY_ShaderLex_CLASS(YY_ShaderLex_CONSTRUCTOR_PARAM) YY_ShaderLex_CONSTRUCTOR_INIT
{yy_initialize();
 YY_ShaderLex_CONSTRUCTOR_CODE;
}
YY_ShaderLex_CLASS::~YY_ShaderLex_CLASS() 
{YY_ShaderLex_DESTRUCTOR_CODE;
 if(YY_ShaderLex_CURRENT_BUFFER)
  YY_ShaderLex_DELETE_BUFFER(YY_ShaderLex_CURRENT_BUFFER);
}

#endif


#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

#ifndef YY_USER_INIT
#define YY_USER_INIT
#endif

/* % data tables for the DFA go here */ 
#define YY_END_OF_BUFFER 55
typedef int yy_state_type;
static const short int yy_accept[120] =
    {   0,
       48,   48,    0,    0,   55,   53,   50,   53,   53,    5,
       53,   11,   12,    3,    1,    9,    2,    8,    4,   47,
       10,    7,   19,   17,   18,   48,   48,   13,   14,    6,
       48,   48,   48,   48,   48,   48,   48,   48,   15,   53,
       16,   51,   52,   25,   49,    0,    0,   30,   20,   28,
       31,   26,   32,   27,   45,   44,   29,   46,   47,   48,
       48,   23,   24,   22,   48,   42,   48,   48,   48,   37,
       48,   48,   48,   48,   48,   48,   21,    0,   45,    0,
        0,   47,   48,   48,   36,   48,   48,   48,   48,   48,
       48,    0,   45,    0,    0,   46,   47,   48,   35,   38,

       48,   48,   48,   48,   48,    0,   45,   34,   48,   48,
       48,   48,   40,   43,   39,   48,   33,   41,    0
    } ;

static const YY_CHAR yy_ec[128] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    1,    1,    5,    6,    1,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   16,   17,   18,
       19,   20,    1,    1,   21,   21,   21,   21,   22,   21,
       21,   21,   23,   21,   21,   21,   21,   21,   21,   24,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       25,    1,   26,   27,   21,    1,   28,   21,   29,   30,

       31,   32,   33,   34,   35,   21,   21,   36,   21,   37,
       38,   21,   21,   39,   40,   41,   42,   43,   44,   21,
       21,   21,   45,   46,   47,    1,    1
    } ;

static const YY_CHAR yy_meta[48] =
    {   0,
        1,    1,    1,    2,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    1,    4,    1,    1,    1,    1,    1,
        4,    4,    4,    4,    1,    1,    1,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    1,    1,    1
    } ;

static const short int yy_base[125] =
    {   0,
        0,    0,  213,  212,  213,  216,  216,  193,   44,  192,
      204,  216,  216,  190,   39,  216,   41,  193,   36,   39,
      216,  216,  188,  187,  186,  189,   41,  216,  216,  216,
       36,   47,   48,   50,   53,   51,   56,   54,  216,  157,
      216,  216,  216,  216,  216,  198,   63,  216,  216,  216,
      216,  216,  216,  216,   58,  216,  216,   75,   81,  188,
       89,  216,  216,  216,  185,  184,   62,   60,   66,  183,
       80,   92,   76,   94,   95,   96,  216,  104,  103,  111,
      182,  114,   98,  107,  181,  113,  102,  115,  120,  122,
      124,  180,  179,  130,  178,  177,  176,  126,  175,  161,

      128,  129,  133,  131,  136,  160,  159,  153,  132,  139,
      141,  138,  149,  147,  143,  142,  140,   64,  216,  177,
      180,  182,   68,  185
    } ;

static const short int yy_def[125] =
    {   0,
      119,    1,  120,  120,  119,  119,  119,  119,  121,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  122,
      119,  119,  119,  119,  119,  123,  123,  119,  119,  119,
      123,  123,  123,  123,  123,  123,  123,  123,  119,  119,
      119,  119,  119,  119,  119,  124,  121,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  122,  122,
      122,  119,  119,  119,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  119,  119,  119,  119,
      119,  122,  123,  123,  123,  123,  123,  123,  123,  123,
      123,  119,  119,  119,  119,  119,  119,  123,  123,  123,

      123,  123,  123,  123,  123,  119,  119,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,    0,  119,
      119,  119,  119,  119
    } ;

static const short int yy_nxt[264] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   26,   26,   27,   28,   29,   30,   26,   31,   26,
       32,   33,   26,   26,   34,   26,   26,   26,   35,   36,
       26,   26,   37,   38,   39,   40,   41,   45,   51,   56,
       60,   58,   53,   59,   57,   60,   46,   52,   46,   54,
       61,   60,   60,   66,   60,   60,   45,   60,   60,   61,
       60,   65,   55,   67,   60,   46,   60,   46,   60,   78,
       60,   70,   68,   71,   72,   69,   75,   76,   78,   79,
       60,   73,   74,   58,   60,   59,   80,   83,   81,   84,

       81,  119,   61,   82,   85,   80,   60,   86,   60,   60,
       60,   61,   60,   92,   88,   92,   60,   79,   93,   87,
       95,   60,   95,   90,   94,   96,  119,   60,   82,   60,
       91,  101,   89,   94,   60,   98,   60,   99,   60,  106,
       60,  106,   60,   60,  107,   60,   60,   60,  100,  102,
       60,  103,   60,   60,   60,   60,   60,   60,  109,  105,
      111,   60,  104,   60,  108,  110,  113,   60,  112,  116,
      114,  115,  118,  107,  107,   60,  117,   42,   42,   42,
       42,   47,   47,   47,   60,   60,   46,   46,   46,   60,
       97,   96,   96,   93,   93,   60,   97,   60,   60,   60,

      119,   45,   77,   60,   64,   63,   62,   55,   50,   49,
       48,   44,  119,   43,   43,    5,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119
    } ;

static const short int yy_chk[264] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    9,   15,   19,
       31,   20,   17,   20,   19,   27,    9,   15,    9,   17,
       20,   32,   33,   27,   34,   36,   47,   35,   38,   20,
       37,  123,   55,   31,   68,   47,   67,   47,  118,   55,
       69,   34,   32,   35,   36,   33,   37,   38,   55,   58,
       73,   36,   36,   59,   71,   59,   58,   67,   61,   68,

       61,   61,   59,   61,   69,   58,   72,   71,   74,   75,
       76,   59,   83,   78,   73,   78,   87,   79,   78,   72,
       80,   84,   80,   75,   79,   80,   82,   86,   82,   88,
       76,   87,   74,   79,   89,   83,   90,   84,   91,   94,
       98,   94,  101,  102,   94,  104,  109,  103,   86,   88,
      105,   89,  112,  110,  117,  111,  116,  115,  101,   91,
      103,  114,   90,  113,   98,  102,  105,  108,  104,  111,
      109,  110,  116,  107,  106,  100,  112,  120,  120,  120,
      120,  121,  121,  121,  122,  122,  124,  124,  124,   99,
       97,   96,   95,   93,   92,   85,   81,   70,   66,   65,

       60,   46,   40,   26,   25,   24,   23,   18,   14,   11,
       10,    8,    5,    4,    3,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119
    } ;

static yy_state_type yy_last_accepting_state;
static YY_CHAR *yy_last_accepting_cpos;

#if YY_ShaderLex_DEBUG != 0
static const short int yy_rule_linenum[54] =
    {   0,
       51,   52,   53,   54,   55,   56,   57,   58,   59,   60,
       61,   62,   63,   64,   65,   66,   67,   68,   69,   70,
       71,   72,   73,   74,   75,   76,   77,   78,   79,   80,
       81,   82,   84,   85,   86,   87,   88,   89,   90,   91,
       92,   93,   94,   96,  100,  101,  102,  107,  112,  117,
      121,  123,  128
    } ;

#endif
/* the intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#line 376 "/usr/local/lib/flexskel.cc"
#ifndef YY_USE_CLASS
static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
#else
#define yy_get_previous_state() ((yy_state_type)(yy_get_previous_state_()))
#define yy_try_NUL_trans(c) ((yy_state_type)(yy_try_NUL_trans_(c)))
#endif

#ifndef YY_USE_CLASS
#ifdef YY_ShaderLex_LEX_DEFINED
YY_ShaderLex_LEX_RETURN YY_ShaderLex_LEX ( YY_ShaderLex_LEX_PARAM )
YY_ShaderLex_LEX_PARAM_DEF
#else
YY_DECL
#endif
#else
YY_ShaderLex_LEX_RETURN YY_ShaderLex_CLASS::YY_ShaderLex_LEX ( YY_ShaderLex_LEX_PARAM)

#endif
    {
    register yy_state_type yy_current_state;
    register YY_ShaderLex_CHAR *yy_cp, *yy_bp;
    register int yy_act;

/* % user's declarations go here */ 


/* % end of prolog */ 
#line 401 "/usr/local/lib/flexskel.cc"

    if ( yy_init )
	{
	 
	 {
	 YY_USER_INIT;
	 }
	if ( ! yy_start )
	    yy_start = 1;       /* first start state */

	if ( ! yy___in )
	    yy___in = YY_ShaderLex_IFILE_DEFAULT;

	if ( ! yy___out )
	    yy___out = YY_ShaderLex_OFILE_DEFAULT;

	if ( YY_ShaderLex_CURRENT_BUFFER )
	    YY_ShaderLex_INIT_BUFFER( YY_ShaderLex_CURRENT_BUFFER, yy___in );
	else
	    YY_ShaderLex_CURRENT_BUFFER = YY_ShaderLex_CREATE_BUFFER( yy___in, YY_BUF_SIZE );

	YY_ShaderLex_LOAD_BUFFER_STATE();
	yy_init=0;
	}

    while ( 1 )         /* loops until end-of-file is reached */
	{
/* % yymore()-related code goes here */ 
#line 429 "/usr/local/lib/flexskel.cc"
	yy_cp = yy_c_buf_p;

	/* support of yy___text */
	*yy_cp = yy_hold_char;

	/* yy_bp points to the position in yy_ch_buf of the start of the
	 * current run.
	 */
	yy_bp = yy_cp;

/* % code to set up and find next match goes here */ 
	yy_current_state = yy_start;
yy_match:
	do
	    {
	    register YY_CHAR yy_c = yy_ec[*yy_cp];
	    if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = yy_def[yy_current_state];
		if ( yy_current_state >= 120 )
		    yy_c = yy_meta[yy_c];
		}
	    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	    ++yy_cp;
	    }
	while ( yy_current_state != 119 );
	yy_cp = yy_last_accepting_cpos;
	yy_current_state = yy_last_accepting_state;
#line 440 "/usr/local/lib/flexskel.cc"

yy_find_action:
/* % code to find the action number goes here */ 
	yy_act = yy_accept[yy_current_state];
#line 443 "/usr/local/lib/flexskel.cc"

	YY_DO_BEFORE_ACTION;
	YY_USER_ACTION;

do_action:      /* this label is used only to access EOF actions */
#if YY_ShaderLex_DEBUG != 0
	if ( yy___flex_debug )
		{
		if ( yy_act == 0 )
#ifndef YY_ShaderLex_IOSTREAM
			fprintf( yy___stderr , "--scanner backtracking\n" );
#else
			yy___stderr <<"--scanner backtracking"<<endl;
#endif
		else if ( yy_act < YY_END_OF_BUFFER -1 )
#ifndef YY_ShaderLex_IOSTREAM
			fprintf( yy___stderr , 
			 "--accepting rule at line %d (\"%s\")\n",
			 yy_rule_linenum[yy_act], yy___text );
#else
			yy___stderr <<"--accepting rule at line "
                          <<(int)yy_rule_linenum[yy_act]
                          <<" (\""<<(char *)yy___text<<"\")"<<endl;
#endif
		else if ( yy_act == YY_END_OF_BUFFER -1 )
#ifndef YY_ShaderLex_IOSTREAM
			fprintf( yy___stderr , 
			 "--accepting default rule (\"%s\")\n",
			 yy___text );
#else
			yy___stderr <<"--accepting default rule"
                          <<" (\""<<(char *)yy___text<<"\")"<<endl;
#endif
		else if ( yy_act == YY_END_OF_BUFFER )
#ifndef YY_ShaderLex_IOSTREAM
			fprintf( yy___stderr , "--(end of buffer or a NUL)\n" );
#else
			yy___stderr <<"--(end of buffer or a NUL)"<<endl;
#endif
		else
#ifndef YY_ShaderLex_IOSTREAM
			fprintf( yy___stderr , "--EOF\n" );
#else
			yy___stderr <<"--EOF"<<endl;
#endif
		}
#endif
	switch ( yy_act )
	    {
/* % actions go here */ 
	    case 0: /* must backtrack */
	    /* undo the effects of YY_DO_BEFORE_ACTION */
	    *yy_cp = yy_hold_char;
	    yy_cp = yy_last_accepting_cpos;
	    yy_current_state = yy_last_accepting_state;
	    goto yy_find_action;

case 1:
#line 51 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
return *yytext;
	YY_BREAK
case 2:
#line 52 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
return *yytext;
	YY_BREAK
case 3:
#line 53 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
return *yytext;
	YY_BREAK
case 4:
#line 54 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
return *yytext;
	YY_BREAK
case 5:
#line 55 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
return *yytext;
	YY_BREAK
case 6:
#line 56 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
return *yytext;
	YY_BREAK
case 7:
#line 57 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
return *yytext;
	YY_BREAK
case 8:
#line 58 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
return *yytext;
	YY_BREAK
case 9:
#line 59 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
return *yytext;
	YY_BREAK
case 10:
#line 60 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
return *yytext;
	YY_BREAK
case 11:
#line 61 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
return *yytext;
	YY_BREAK
case 12:
#line 62 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
return *yytext;
	YY_BREAK
case 13:
#line 63 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
return *yytext;
	YY_BREAK
case 14:
#line 64 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
return *yytext;
	YY_BREAK
case 15:
#line 65 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
return *yytext;
	YY_BREAK
case 16:
#line 66 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
return *yytext;
	YY_BREAK
case 17:
#line 67 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
return *yytext;
	YY_BREAK
case 18:
#line 68 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
return *yytext;
	YY_BREAK
case 19:
#line 69 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
return *yytext;
	YY_BREAK
case 20:
#line 70 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
return ShaderYacc::AND;
	YY_BREAK
case 21:
#line 71 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
return ShaderYacc::OR;
	YY_BREAK
case 22:
#line 72 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
return ShaderYacc::GE;
	YY_BREAK
case 23:
#line 73 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
return ShaderYacc::LE;
	YY_BREAK
case 24:
#line 74 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
return ShaderYacc::EQ;
	YY_BREAK
case 25:
#line 75 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
return ShaderYacc::NE;
	YY_BREAK
case 26:
#line 76 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
return ShaderYacc::PE;
	YY_BREAK
case 27:
#line 77 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
return ShaderYacc::ME;
	YY_BREAK
case 28:
#line 78 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
return ShaderYacc::TE;
	YY_BREAK
case 29:
#line 79 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
return ShaderYacc::DE;
	YY_BREAK
case 30:
#line 80 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
return ShaderYacc::RE;
	YY_BREAK
case 31:
#line 81 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
return ShaderYacc::PP;
	YY_BREAK
case 32:
#line 82 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
return ShaderYacc::MM;
	YY_BREAK
case 33:
#line 84 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
return ShaderYacc::VECTOR;
	YY_BREAK
case 34:
#line 85 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
return ShaderYacc::COLOR;
	YY_BREAK
case 35:
#line 86 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
return ShaderYacc::ELSE;
	YY_BREAK
case 36:
#line 87 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
return ShaderYacc::FOR;
	YY_BREAK
case 37:
#line 88 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
return ShaderYacc::IF;
	YY_BREAK
case 38:
#line 89 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
return ShaderYacc::REAL;
	YY_BREAK
case 39:
#line 90 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
return ShaderYacc::STRING;
	YY_BREAK
case 40:
#line 91 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
return ShaderYacc::WHILE;
	YY_BREAK
case 41:
#line 92 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
return ShaderYacc::SURFACE;
	YY_BREAK
case 42:
#line 93 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
return ShaderYacc::PI;
	YY_BREAK
case 43:
#line 94 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
return ShaderYacc::SHADER;
	YY_BREAK
case 44:
#line 96 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
{
                                  BEGIN(SKIP_REST_OF_LINE);
                                }        
	YY_BREAK
case 45:
#line 101 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
case 46:
#line 102 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
case 47:
#line 102 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
{
                                  yylval.number = atof(yytext);
                                  return ShaderYacc::NUMBER;
                                }
	YY_BREAK
case 48:
#line 107 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
{
                                  yylval.id = new RCString(yytext);
                                  return ShaderYacc::IDENTIFIER;
				}
	YY_BREAK
case 49:
#line 112 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
{
                                  yylval.id = new RCString(yytext);
                                  return ShaderYacc::ANYSTRING;
				}
	YY_BREAK
case 50:
#line 117 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
{ 
                                  myLineNo++;
                                }
	YY_BREAK
case 51:
#line 121 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
;
	YY_BREAK
case 52:
#line 123 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
{
                                  myLineNo++;
                                  BEGIN(0);
                                 }
	YY_BREAK
case 53:
#line 128 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
;
	YY_BREAK
case 54:
#line 130 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(SKIP_REST_OF_LINE):
    yyterminate();
#line 493 "/usr/local/lib/flexskel.cc"

	    case YY_END_OF_BUFFER:
		{
		/* amount of text matched not including the EOB char */
		int yy_amount_of_matched_text = yy_cp - yy___text - 1;

		/* undo the effects of YY_DO_BEFORE_ACTION */
		*yy_cp = yy_hold_char;

		/* note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the end-
		 * of-buffer state).  Contrast this with the test in yyinput().
		 */
		if ( yy_c_buf_p <= &YY_ShaderLex_CURRENT_BUFFER->yy_ch_buf[yy_n_chars] )
		    /* this was really a NUL */
		    {
		    yy_state_type yy_next_state;

		    yy_c_buf_p = yy___text + yy_amount_of_matched_text;

		    yy_current_state = yy_get_previous_state();

		    /* okay, we're now positioned to make the
		     * NUL transition.  We couldn't have
		     * yy_get_previous_state() go ahead and do it
		     * for us because it doesn't know how to deal
		     * with the possibility of jamming (and we
		     * don't want to build jamming into it because
		     * then it will run more slowly)
		     */

		    yy_next_state = yy_try_NUL_trans( yy_current_state );

		    yy_bp = yy___text + YY_MORE_ADJ;

		    if ( yy_next_state )
			{
			/* consume the NUL */
			yy_cp = ++yy_c_buf_p;
			yy_current_state = yy_next_state;
			goto yy_match;
			}

		    else
			{
/* % code to do backtracking for compressed tables and set up yy_cp goes here */ 
			    yy_cp = yy_last_accepting_cpos;
			    yy_current_state = yy_last_accepting_state;
#line 541 "/usr/local/lib/flexskel.cc"
			goto yy_find_action;
			}
		    }

		else switch ( yy_get_next_buffer() )
		    {
		    case EOB_ACT_END_OF_FILE:
			{
			yy_did_buffer_switch_on_eof = 0;

			if ( yywrap() )
			    {
			    /* note: because we've taken care in
			     * yy_get_next_buffer() to have set up yy___text,
			     * we can now set up yy_c_buf_p so that if some
			     * total hoser (like flex itself) wants
			     * to call the scanner after we return the
			     * YY_NULL, it'll still work - another YY_NULL
			     * will get returned.
			     */
			    yy_c_buf_p = yy___text + YY_MORE_ADJ;

			    yy_act = YY_STATE_EOF((yy_start - 1) / 2);
			    goto do_action;
			    }

			else
			    {
			    if ( ! yy_did_buffer_switch_on_eof )
				YY_NEW_FILE;
			    }
			}
			break;

		    case EOB_ACT_CONTINUE_SCAN:
			yy_c_buf_p = yy___text + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yy___text + YY_MORE_ADJ;
			goto yy_match;

		    case EOB_ACT_LAST_MATCH:
			yy_c_buf_p =
			    &YY_ShaderLex_CURRENT_BUFFER->yy_ch_buf[yy_n_chars];

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yy___text + YY_MORE_ADJ;
			goto yy_find_action;
		    }
		break;
		}

	    default:
#if YY_ShaderLex_DEBUG != 0
#ifndef YY_ShaderLex_IOSTREAM
		fprintf(yy___stderr , "action # %d\n", yy_act );
#else
		yy___stderr <<"action # "<<(int)yy_act<<endl;
#endif
#endif
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	    }
	}
	yyterminate();/* avoid the no return value error message on MS-C7/dos */
    }


/* yy_get_next_buffer - try to read in a new buffer
 *
 * synopsis
 *     int yy_get_next_buffer();
 *     
 * returns a code representing an action
 *     EOB_ACT_LAST_MATCH - 
 *     EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *     EOB_ACT_END_OF_FILE - end of file
 */
#ifndef YY_USE_CLASS
static int yy_get_next_buffer()
#else
int YY_ShaderLex_CLASS::yy_get_next_buffer()
#endif
    {
    register YY_ShaderLex_CHAR *dest = YY_ShaderLex_CURRENT_BUFFER->yy_ch_buf;
    register YY_ShaderLex_CHAR *source = yy___text - 1; /* copy prev. char, too */
    register int number_to_move, i;
    int ret_val;

    if ( yy_c_buf_p > &YY_ShaderLex_CURRENT_BUFFER->yy_ch_buf[yy_n_chars + 1] )
	YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

    /* try to read more data */

    /* first move last chars to start of buffer */
    number_to_move = yy_c_buf_p - yy___text;

    for ( i = 0; i < number_to_move; ++i )
	*(dest++) = *(source++);

    if ( YY_ShaderLex_CURRENT_BUFFER->yy_eof_status != EOF_NOT_SEEN )
	/* don't do the read, it's not guaranteed to return an EOF,
	 * just force an EOF
	 */
	yy_n_chars = 0;

    else
	{
	int num_to_read = YY_ShaderLex_CURRENT_BUFFER->yy_buf_size - number_to_move - 1;

	if ( num_to_read > YY_READ_BUF_SIZE )
	    num_to_read = YY_READ_BUF_SIZE;

	else if ( num_to_read <= 0 )
	    YY_FATAL_ERROR( "fatal error - scanner input buffer overflow" );

	/* read in more data */
	YY_INPUT( (&YY_ShaderLex_CURRENT_BUFFER->yy_ch_buf[number_to_move]),
		  yy_n_chars, num_to_read );
	}

    if ( yy_n_chars == 0 )
	{
	if ( number_to_move - YY_MORE_ADJ == 1 )
	    {
	    ret_val = EOB_ACT_END_OF_FILE;
	    YY_ShaderLex_CURRENT_BUFFER->yy_eof_status = EOF_DONE;
	    }

	else
	    {
	    ret_val = EOB_ACT_LAST_MATCH;
	    YY_ShaderLex_CURRENT_BUFFER->yy_eof_status = EOF_PENDING;
	    }
	}

    else
	ret_val = EOB_ACT_CONTINUE_SCAN;

    yy_n_chars += number_to_move;
    YY_ShaderLex_CURRENT_BUFFER->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
    YY_ShaderLex_CURRENT_BUFFER->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

    /* yy___text begins at the second character in yy_ch_buf; the first
     * character is the one which preceded it before reading in the latest
     * buffer; it needs to be kept around in case it's a newline, so
     * yy_get_previous_state() will have with '^' rules active
     */

    yy___text = &YY_ShaderLex_CURRENT_BUFFER->yy_ch_buf[1];

    return ( ret_val );
    }


/* yy_get_previous_state - get the state just before the EOB char was reached
 *
 * synopsis
 *     yy_state_type yy_get_previous_state();
 */

#ifndef YY_USE_CLASS
static yy_state_type yy_get_previous_state()
#else
long YY_ShaderLex_CLASS::yy_get_previous_state_()
#endif
    {
    register yy_state_type yy_current_state;
    register YY_ShaderLex_CHAR *yy_cp;

/* % code to get the start state into yy_current_state goes here */ 
    yy_current_state = yy_start;
#line 717 "/usr/local/lib/flexskel.cc"

    for ( yy_cp = yy___text + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
	{
/* % code to find the next state goes here */ 
	register YY_CHAR yy_c = (*yy_cp ? yy_ec[*yy_cp] : 1);
	if ( yy_accept[yy_current_state] )
	    {
	    yy_last_accepting_state = yy_current_state;
	    yy_last_accepting_cpos = yy_cp;
	    }
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	    {
	    yy_current_state = yy_def[yy_current_state];
	    if ( yy_current_state >= 120 )
		yy_c = yy_meta[yy_c];
	    }
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
#line 721 "/usr/local/lib/flexskel.cc"
	}

#ifndef YY_USE_CLASS
    return ( yy_current_state );
#else
    return (long)( yy_current_state );
#endif
    }


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *     next_state = yy_try_NUL_trans( current_state );
 */

#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( register yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
register yy_state_type yy_current_state;
#endif
#else
long YY_ShaderLex_CLASS::yy_try_NUL_trans_(long yy_current_state_)
#endif

    {
#ifndef YY_USE_CLASS
#else
    yy_state_type yy_current_state=(yy_state_type)yy_current_state_;
#endif
    register int yy_is_jam;
/* % code to find the next state, and perhaps do backtracking, goes here */ 
    register YY_CHAR *yy_cp = yy_c_buf_p;

    register YY_CHAR yy_c = 1;
    if ( yy_accept[yy_current_state] )
	{
	yy_last_accepting_state = yy_current_state;
	yy_last_accepting_cpos = yy_cp;
	}
    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	{
	yy_current_state = yy_def[yy_current_state];
	if ( yy_current_state >= 120 )
	    yy_c = yy_meta[yy_c];
	}
    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
    yy_is_jam = (yy_current_state == 119);
#line 755 "/usr/local/lib/flexskel.cc"

#ifndef YY_USE_CLASS
    return ( yy_is_jam ? 0 : yy_current_state );
#else
    return (long)( yy_is_jam ? 0 : yy_current_state );
#endif
    }

#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
static void yyunput( YY_ShaderLex_CHAR c, register YY_ShaderLex_CHAR *yy_bp )
#else
static void yyunput( c, yy_bp )
YY_ShaderLex_CHAR c;
register YY_ShaderLex_CHAR *yy_bp;
#endif
#else
void YY_ShaderLex_CLASS::yyunput( YY_ShaderLex_CHAR c, YY_ShaderLex_CHAR *yy_bp )
#endif

    {
    register YY_ShaderLex_CHAR *yy_cp = yy_c_buf_p;

    /* undo effects of setting up yy___text */
    *yy_cp = yy_hold_char;

    if ( yy_cp < YY_ShaderLex_CURRENT_BUFFER->yy_ch_buf + 2 )
	{ /* need to shift things up to make room */
	register int number_to_move = yy_n_chars + 2; /* +2 for EOB chars */
	register YY_ShaderLex_CHAR *dest =
	    &YY_ShaderLex_CURRENT_BUFFER->yy_ch_buf[YY_ShaderLex_CURRENT_BUFFER->yy_buf_size + 2];
	register YY_ShaderLex_CHAR *source =
	    &YY_ShaderLex_CURRENT_BUFFER->yy_ch_buf[number_to_move];

	while ( source > YY_ShaderLex_CURRENT_BUFFER->yy_ch_buf )
	    *--dest = *--source;

	yy_cp += dest - source;
	yy_bp += dest - source;
	yy_n_chars = YY_ShaderLex_CURRENT_BUFFER->yy_buf_size;

	if ( yy_cp < YY_ShaderLex_CURRENT_BUFFER->yy_ch_buf + 2 )
	    YY_FATAL_ERROR( "flex scanner push-back overflow" );
	}

    if ( yy_cp > yy_bp && yy_cp[-1] == '\n' )
	yy_cp[-2] = '\n';

    *--yy_cp = c;

    /* note: the formal parameter *must* be called "yy_bp" for this
     *       macro to now work correctly
     */
    YY_DO_BEFORE_ACTION; /* set up yy___text again */
    }

#ifndef YY_USE_CLASS
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
#else
int YY_ShaderLex_CLASS::input()
#endif
    {
    int c;
    YY_ShaderLex_CHAR *yy_cp = yy_c_buf_p;

    *yy_cp = yy_hold_char;

    if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
	{
	/* yy_c_buf_p now points to the character we want to return.
	 * If this occurs *before* the EOB characters, then it's a
	 * valid NUL; if not, then we've hit the end of the buffer.
	 */
	if ( yy_c_buf_p < &YY_ShaderLex_CURRENT_BUFFER->yy_ch_buf[yy_n_chars] )
	    /* this was really a NUL */
	    *yy_c_buf_p = '\0';

	else
	    { /* need more input */
	    yy___text = yy_c_buf_p;
	    ++yy_c_buf_p;

	    switch ( yy_get_next_buffer() )
		{
		case EOB_ACT_END_OF_FILE:
		    {
		    if ( yywrap() )
			{
			yy_c_buf_p = yy___text + YY_MORE_ADJ;
			return ( EOF );
			}

		    YY_NEW_FILE;
#ifndef YY_USE_CLASS
#ifdef __cplusplus
		    return ( yyinput() );
#else
		    return ( input() );
#endif
#else
		    return ( input() );
#endif
		    }
		    break;

		case EOB_ACT_CONTINUE_SCAN:
		    yy_c_buf_p = yy___text + YY_MORE_ADJ;
		    break;

		case EOB_ACT_LAST_MATCH:
#ifndef YY_USE_CLASS
#ifdef __cplusplus
		    YY_FATAL_ERROR( "unexpected last match in yyinput()" );
#else
		    YY_FATAL_ERROR( "unexpected last match in input()" );
#endif
#else
		    YY_FATAL_ERROR( "unexpected last match in YY_ShaderLex_CLASS::input()" );
#endif
		}
	    }
	}

    c = *yy_c_buf_p;
    yy_hold_char = *++yy_c_buf_p;

    return ( c );
    }


#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
void YY_ShaderLex_RESTART( YY_ShaderLex_IFILE  *input_file )
#else
void YY_ShaderLex_RESTART( input_file )
YY_ShaderLex_IFILE  *input_file;
#endif
#else
void YY_ShaderLex_CLASS::YY_ShaderLex_RESTART ( YY_ShaderLex_IFILE  *input_file )
#endif

    {
    YY_ShaderLex_INIT_BUFFER( YY_ShaderLex_CURRENT_BUFFER, input_file );
    YY_ShaderLex_LOAD_BUFFER_STATE();
    }


#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
void YY_ShaderLex_SWITCH_TO_BUFFER( YY_BUFFER_STATE new_buffer )
#else
void YY_ShaderLex_SWITCH_TO_BUFFER( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
#else
void YY_ShaderLex_CLASS::YY_ShaderLex_SWITCH_TO_BUFFER( YY_BUFFER_STATE new_buffer )
#endif

    {
    if ( YY_ShaderLex_CURRENT_BUFFER == new_buffer )
	return;

    if ( YY_ShaderLex_CURRENT_BUFFER )
	{
	/* flush out information for old buffer */
	*yy_c_buf_p = yy_hold_char;
	YY_ShaderLex_CURRENT_BUFFER->yy_buf_pos = yy_c_buf_p;
	YY_ShaderLex_CURRENT_BUFFER->yy_n_chars = yy_n_chars;
	}

    YY_ShaderLex_CURRENT_BUFFER = new_buffer;
    YY_ShaderLex_LOAD_BUFFER_STATE();

    /* we don't actually know whether we did this switch during
     * EOF (yywrap()) processing, but the only time this flag
     * is looked at is after yywrap() is called, so it's safe
     * to go ahead and always set it.
     */
    yy_did_buffer_switch_on_eof = 1;
    }


#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
void YY_ShaderLex_LOAD_BUFFER_STATE( void )
#else
void YY_ShaderLex_LOAD_BUFFER_STATE()
#endif
#else
void YY_ShaderLex_CLASS::YY_ShaderLex_LOAD_BUFFER_STATE(  )
#endif

    {
    yy_n_chars = YY_ShaderLex_CURRENT_BUFFER->yy_n_chars;
    yy___text = yy_c_buf_p = YY_ShaderLex_CURRENT_BUFFER->yy_buf_pos;
    yy___in = YY_ShaderLex_CURRENT_BUFFER->yy_input_file;
    yy_hold_char = *yy_c_buf_p;
    }


#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE YY_ShaderLex_CREATE_BUFFER( YY_ShaderLex_IFILE  *file, int size )
#else
YY_BUFFER_STATE YY_ShaderLex_CREATE_BUFFER( file, size )
YY_ShaderLex_IFILE  *file;
int size;
#endif
#else
YY_BUFFER_STATE YY_ShaderLex_CLASS::YY_ShaderLex_CREATE_BUFFER( YY_ShaderLex_IFILE  *file, int size )
#endif

    {
    YY_BUFFER_STATE b;

    b = (YY_BUFFER_STATE) malloc( sizeof( struct yy_buffer_state ) );

    if ( ! b )
	YY_FATAL_ERROR( "out of dynamic memory in YY_ShaderLex_CREATE_BUFFER()" );

    b->yy_buf_size = size;

    /* yy_ch_buf has to be 2 characters longer than the size given because
     * we need to put in 2 end-of-buffer characters.
     */
    b->yy_ch_buf = (YY_ShaderLex_CHAR *) malloc( (unsigned) (b->yy_buf_size + 2) );

    if ( ! b->yy_ch_buf )
	YY_FATAL_ERROR( "out of dynamic memory in YY_ShaderLex_CREATE_BUFFER()" );

    YY_ShaderLex_INIT_BUFFER( b, file );

    return ( b );
    }


#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
void YY_ShaderLex_DELETE_BUFFER( YY_BUFFER_STATE b )
#else
void YY_ShaderLex_DELETE_BUFFER( b )
YY_BUFFER_STATE b;
#endif
#else
void YY_ShaderLex_CLASS::YY_ShaderLex_DELETE_BUFFER( YY_BUFFER_STATE b )
#endif

    {
    if ( b == YY_ShaderLex_CURRENT_BUFFER )
	YY_ShaderLex_CURRENT_BUFFER = (YY_BUFFER_STATE) 0;

    free( (char *) b->yy_ch_buf );
    free( (char *) b );
    }


#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
void YY_ShaderLex_INIT_BUFFER( YY_BUFFER_STATE b, YY_ShaderLex_IFILE  *file )
#else
void YY_ShaderLex_INIT_BUFFER( b, file )
YY_BUFFER_STATE b;
YY_ShaderLex_IFILE  *file;
#endif
#else
void YY_ShaderLex_CLASS::YY_ShaderLex_INIT_BUFFER( YY_BUFFER_STATE b, YY_ShaderLex_IFILE  *file)
#endif

    {
    b->yy_input_file = file;

    /* we put in the '\n' and start reading from [1] so that an
     * initial match-at-newline will be true.
     */

    b->yy_ch_buf[0] = '\n';
    b->yy_n_chars = 1;

    /* we always need two end-of-buffer characters.  The first causes
     * a transition to the end-of-buffer state.  The second causes
     * a jam in that state.
     */
    b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;
    b->yy_ch_buf[2] = YY_END_OF_BUFFER_CHAR;

    b->yy_buf_pos = &b->yy_ch_buf[1];

    b->yy_eof_status = EOF_NOT_SEEN;
    }
#line 130 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/texture/src/ShaderLex.l"

