#ifndef FLEX_HEADER_BSDLLex_h
#define FLEX_HEADER_BSDLLex_h
#line 25 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/component/src/BSDLLex.l"
#include "BSDLYacc.h"
#define YY_BSDLLex_CHAR char
#line 1 "/usr/local/lib/flexskel.h"
/* A lexical scanner header generated by flex */
/* MODIFIED FOR C++ CLASS BY Alain Coetmeur: coetmeur(at)icdc.fr */
/* Note that (at) mean the 'at' symbol that I cannot write */
/* because it is expanded to the class name */
/* made at Informatique-CDC, Research&development department */
/* company from the Caisse Des Depots et Consignations */


/*********************************************/
/* SYSTEM dependent declaration, includes... */
/*********************************************/
/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif
#ifdef __cplusplus
#ifndef YY_USE_PROTOS
#define YY_USE_PROTOS
#endif
#ifndef YY_USE_CLASS
#define YY_USE_CLASS
#endif
#else	/* ! __cplusplus */
#ifdef __STDC__
#ifdef __GNUC__
#else
#endif	/* __GNUC__ */
#ifndef YY_USE_PROTOS
#define YY_USE_PROTOS
#endif
#endif	/* __STDC__ */
#endif	/* ! __cplusplus */
/*********************************************/
/* COMPILER DEPENDENT   MACROS               */
/*********************************************/
/* use prototypes in function declarations */
#ifndef YY_PROTO
#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif
#endif
#include <stdio.h>




/* % here is the declaration from section1 %header{  */ 
#line 34 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/component/src/BSDLLex.l"
#define YY_BSDLLex_DEBUG  1
#line 35 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/component/src/BSDLLex.l"
#define YY_BSDLLex_DEBUG_FLAG  myScannerDebugFlag
#line 36 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/component/src/BSDLLex.l"
#define YY_BSDLLex_DEBUG_INIT  0
#line 38 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/component/src/BSDLLex.l"
#define YY_BSDLLex_CONSTRUCTOR_PARAM  void
#line 39 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/component/src/BSDLLex.l"
#define YY_BSDLLex_CONSTRUCTOR_INIT  : myCurrentLine(1)
#line 40 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/component/src/BSDLLex.l"
#define YY_BSDLLex_CONSTRUCTOR_CODE  
#line 42 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/component/src/BSDLLex.l"
#define YY_BSDLLex_IN  inputFile
#line 44 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/component/src/BSDLLex.l"
#define YY_BSDLLex_MEMBERS                                               \
  public:                                                    \
     const char* getCurrentToken() const { return yytext; }  \
     int getCurrentLine() const { return myCurrentLine; }    \
     const RCString& getCurrentFilename() const              \
     { return myCurrentFilename; }                           \
  private:                                                   \
     int myLineNo;                                           \
     int myCurrentLine;                                      \
     RCString myCurrentFilename;
#line 55 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/component/src/BSDLLex.l"
#define YY_BSDLLex_LEX  scan
#line 56 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/component/src/BSDLLex.l"
#define YY_BSDLLex_LEX_PARAM  YY_BSDLYacc_STYPE& yylval
#line 67 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/component/src/BSDLLex.l"
#line 52 "/usr/local/lib/flexskel.h"

#ifdef YY_USE_CLASS
#ifdef YY_BSDLLex_IOSTREAM
#include <iostream.h>
#define YY_BSDLLex_IFILE  istream
#define YY_BSDLLex_OFILE ostream 
#define YY_BSDLLex_ERRFILE cerr

#ifndef YY_BSDLLex_IFILE_DEFAULT
#define YY_BSDLLex_IFILE_DEFAULT &cin
#endif

#ifndef YY_BSDLLex_OFILE_DEFAULT
#define YY_BSDLLex_OFILE_DEFAULT &cout
#endif

#endif
#endif

#ifndef YY_BSDLLex_IFILE
#define YY_BSDLLex_IFILE FILE 
#endif

#ifndef YY_BSDLLex_OFILE
#define YY_BSDLLex_OFILE FILE 
#endif

#ifndef YY_BSDLLex_ERRFILE
#define YY_BSDLLex_ERRFILE stderr
#endif

#ifndef YY_BSDLLex_IFILE_DEFAULT
#define YY_BSDLLex_IFILE_DEFAULT stdin
#endif

#ifndef YY_BSDLLex_OFILE_DEFAULT
#define YY_BSDLLex_OFILE_DEFAULT stdout
#endif




#ifndef YY_BSDLLex_TEXT
#define YY_BSDLLex_TEXT yytext
#endif
#ifndef YY_BSDLLex_LENG
#define YY_BSDLLex_LENG yyleng
#endif
#ifndef YY_BSDLLex_IN
#define YY_BSDLLex_IN yyin
#endif
#ifndef YY_BSDLLex_OUT
#define YY_BSDLLex_OUT yyout
#endif

#ifndef YY_BSDLLex_LEX_RETURN
#define YY_BSDLLex_LEX_RETURN int
#else
#ifndef YY_BSDLLex_LEX_DEFINED
#define YY_BSDLLex_LEX_DEFINED 
#endif
#endif

#ifndef YY_BSDLLex_LEX
#define YY_BSDLLex_LEX yylex
#else
#ifndef YY_BSDLLex_LEX_DEFINED
#define YY_BSDLLex_LEX_DEFINED 
#endif
#endif

#ifndef YY_BSDLLex_LEX_PARAM
#ifndef YY_USE_PROTOS
#define YY_BSDLLex_LEX_PARAM 
#else
#define YY_BSDLLex_LEX_PARAM void
#endif
#else
#ifndef YY_BSDLLex_LEX_DEFINED
#define YY_BSDLLex_LEX_DEFINED 
#endif
#endif

#ifndef YY_BSDLLex_LEX_PARAM_DEF
#define YY_BSDLLex_LEX_PARAM_DEF
#else
#ifndef YY_BSDLLex_LEX_DEFINED
#define YY_BSDLLex_LEX_DEFINED 
#endif
#endif

#ifndef YY_BSDLLex_RESTART
#define YY_BSDLLex_RESTART yyrestart
#endif
#ifndef YY_BSDLLex_SWITCH_TO_BUFFER
#define YY_BSDLLex_SWITCH_TO_BUFFER yy_switch_to_buffer
#endif
#ifndef YY_BSDLLex_LOAD_BUFFER_STATE
#define YY_BSDLLex_LOAD_BUFFER_STATE yy_load_buffer_state
#endif

#ifndef YY_BSDLLex_CREATE_BUFFER
#define YY_BSDLLex_CREATE_BUFFER yy_create_buffer
#ifndef YY_USE_CLASS
#ifndef yy_new_buffer
#define yy_new_buffer yy_create_buffer
#endif
#endif
#endif
#ifndef YY_BSDLLex_DELETE_BUFFER
#define YY_BSDLLex_DELETE_BUFFER yy_delete_buffer
#endif
#ifndef YY_BSDLLex_INIT_BUFFER
#define YY_BSDLLex_INIT_BUFFER yy_init_buffer
#endif



#ifdef YY_BSDLLex_FLEX_DEBUG
#ifndef YY_BSDLLex_DEBUG
#define YY_BSDLLex_DEBUG 1
#endif
#else
#ifndef YY_BSDLLex_DEBUG
#define YY_BSDLLex_DEBUG 0
#endif
#endif

#if YY_BSDLLex_DEBUG != 0
#ifndef YY_BSDLLex_DEBUG_FLAG
#define YY_BSDLLex_DEBUG_FLAG yy_flex_debug
#endif
#ifndef YY_BSDLLex_DEBUG_INIT
#define YY_BSDLLex_DEBUG_INIT 1
#endif
#endif




#ifndef YY_USE_CLASS
#ifndef YY_BSDLLex_CURRENT_BUFFER
#define YY_BSDLLex_CURRENT_BUFFER yy_current_buffer
#endif
typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern void YY_BSDLLex_RESTART YY_PROTO(( YY_BSDLLex_IFILE *input_file ));
extern void YY_BSDLLex_SWITCH_TO_BUFFER YY_PROTO(( YY_BUFFER_STATE new_buffer ));
extern void YY_BSDLLex_LOAD_BUFFER_STATE YY_PROTO(( void ));
extern YY_BUFFER_STATE YY_BSDLLex_CREATE_BUFFER YY_PROTO(( YY_BSDLLex_IFILE *file, int size ));
extern void YY_BSDLLex_DELETE_BUFFER YY_PROTO(( YY_BUFFER_STATE b ));
extern void YY_BSDLLex_INIT_BUFFER YY_PROTO(( YY_BUFFER_STATE b, YY_BSDLLex_IFILE *file ));

#if YY_BSDLLex_DEBUG != 0
extern int YY_BSDLLex_DEBUG_FLAG ;
#endif
extern YY_BSDLLex_CHAR  *YY_BSDLLex_TEXT;
extern int YY_BSDLLex_LENG;
extern YY_BSDLLex_IFILE *YY_BSDLLex_IN;
extern YY_BSDLLex_OFILE *YY_BSDLLex_OUT;
#ifdef YY_BSDLLex_LEX_DEFINED
extern YY_BSDLLex_LEX_RETURN YY_BSDLLex_LEX ( YY_BSDLLex_LEX_PARAM )
YY_BSDLLex_LEX_PARAM_DEF
#else
#ifndef YY_DECL
extern YY_BSDLLex_LEX_RETURN YY_BSDLLex_LEX ( YY_BSDLLex_LEX_PARAM )
YY_BSDLLex_LEX_PARAM_DEF
#else
/* no declaration if oldstyle flex */
#endif
#endif
#else

#ifndef YY_BSDLLex_CURRENT_BUFFER
#define YY_BSDLLex_CURRENT_BUFFER YY_CURRENT_BUFFER
#endif
#ifndef YY_BSDLLex_CLASS
#define YY_BSDLLex_CLASS BSDLLex
#endif
#ifndef YY_BSDLLex_ECHO
#define YY_BSDLLex_ECHO yy_echo
#endif
#ifdef YY_BSDLLex_ECHO_PURE
#define YY_BSDLLex_ECHO_NOCODE
#endif

#ifndef YY_BSDLLex_ECHO_CODE
#ifndef YY_BSDLLex_IOSTREAM
#define YY_BSDLLex_ECHO_CODE fwrite( (char *) YY_BSDLLex_TEXT, YY_BSDLLex_LENG, 1, YY_BSDLLex_OUT );
#else
#define YY_BSDLLex_ECHO_CODE (YY_BSDLLex_OUT->write( (char *) YY_BSDLLex_TEXT, YY_BSDLLex_LENG));
#endif
#endif

#ifndef YY_BSDLLex_INPUT
#define YY_BSDLLex_INPUT yy_input
#endif
#ifdef YY_BSDLLex_INPUT_PURE
#define YY_BSDLLex_INPUT_NOCODE
#endif

#ifndef YY_BSDLLex_INPUT_CODE
#ifndef YY_BSDLLex_IOSTREAM
#define YY_BSDLLex_INPUT_CODE return result= fread(  buffer, 1,max_size,YY_BSDLLex_IN );
#else
#define YY_BSDLLex_INPUT_CODE if(YY_BSDLLex_IN->eof())  result=0;else {YY_BSDLLex_IN->read(buffer,max_size);result=YY_BSDLLex_IN->gcount();YY_BSDLLex_IN->clear(YY_BSDLLex_IN->rdstate()&(~ios::failbit));if(YY_BSDLLex_IN->bad()) result= -1;} return result;
#endif
#endif

#ifdef YY_BSDLLex_FATAL_ERROR_PURE
#define YY_BSDLLex_FATAL_ERRO_NOCODE
#endif
#ifndef YY_BSDLLex_FATAL_ERROR
#define YY_BSDLLex_FATAL_ERROR yy_fatal_error
#endif

#ifndef YY_BSDLLex_FATAL_ERROR_CODE
#ifndef YY_BSDLLex_IOSTREAM
#define YY_BSDLLex_FATAL_ERROR_CODE fputs( msg, YY_BSDLLex_ERRFILE );putc( '\n', YY_BSDLLex_ERRFILE );exit( 1 );
#else
#define YY_BSDLLex_FATAL_ERROR_CODE YY_BSDLLex_ERRFILE<< msg <<endl;exit( 1 );
#endif
#endif

#ifndef YY_BSDLLex_WRAP
#define YY_BSDLLex_WRAP yy_wrap
#endif
#ifdef YY_BSDLLex_WRAP_PURE
#define YY_BSDLLex_WRAP_NOCODE
#endif
#ifndef YY_BSDLLex_WRAP_CODE
#define YY_BSDLLex_WRAP_CODE return 1;
#endif


#ifndef YY_BSDLLex_INHERIT
#define YY_BSDLLex_INHERIT
#endif
#ifndef YY_BSDLLex_MEMBERS
#define YY_BSDLLex_MEMBERS 
#endif
#ifndef YY_BSDLLex_CONSTRUCTOR_PARAM
#define YY_BSDLLex_CONSTRUCTOR_PARAM
#endif
#ifndef YY_BSDLLex_CONSTRUCTOR_CODE
#define YY_BSDLLex_CONSTRUCTOR_CODE
#endif
#ifndef YY_BSDLLex_CONSTRUCTOR_INIT
#define YY_BSDLLex_CONSTRUCTOR_INIT
#endif
#ifndef YY_BSDLLex_DESTRUCTOR_CODE
#define YY_BSDLLex_DESTRUCTOR_CODE
#endif
typedef struct yy_buffer_state *YY_BUFFER_STATE;

class YY_BSDLLex_CLASS YY_BSDLLex_INHERIT
{
 private:/* data */
 YY_BSDLLex_CHAR  *yy_c_buf_p;
 YY_BSDLLex_CHAR  yy_hold_char;
 int yy_n_chars;
 int yy_init;
 int yy_start;
 int yy_did_buffer_switch_on_eof;
 private: /* functions */
 void yy_initialize();
 int input();
 int yyinput() {return input();};
 int yy_get_next_buffer();
 void yyunput( YY_BSDLLex_CHAR  c, YY_BSDLLex_CHAR  *buf_ptr );
 /* use long instead of yy_state_type because it is undef */
 long yy_get_previous_state_ ( void );
 long yy_try_NUL_trans_  ( long current_state_ );
 protected:/* non virtual */
 YY_BUFFER_STATE YY_BSDLLex_CURRENT_BUFFER;
 void YY_BSDLLex_RESTART ( YY_BSDLLex_IFILE *input_file );
 void YY_BSDLLex_SWITCH_TO_BUFFER( YY_BUFFER_STATE new_buffer );
 void YY_BSDLLex_LOAD_BUFFER_STATE( void );
 YY_BUFFER_STATE YY_BSDLLex_CREATE_BUFFER( YY_BSDLLex_IFILE *file, int size );
 void YY_BSDLLex_DELETE_BUFFER( YY_BUFFER_STATE b );
 void YY_BSDLLex_INIT_BUFFER( YY_BUFFER_STATE b, YY_BSDLLex_IFILE *file );
 protected: /* virtual */
 virtual void YY_BSDLLex_ECHO()
#ifdef YY_BSDLLex_ECHO_PURE
  =0
#endif
  ;
 virtual int  YY_BSDLLex_INPUT(char  *buf,int &result,int max_size)
#ifdef YY_BSDLLex_INPUT_PURE
  =0
#endif
  ;
 virtual void  YY_BSDLLex_FATAL_ERROR(char *msg)
#ifdef YY_BSDLLex_FATAL_ERROR_PURE
  =0
#endif
  ;
 virtual int  YY_BSDLLex_WRAP()
#ifdef YY_BSDLLex_WRAP_PURE
  =0
#endif
  ;
 public:
 YY_BSDLLex_CHAR  *YY_BSDLLex_TEXT;
 int YY_BSDLLex_LENG;
 YY_BSDLLex_IFILE *YY_BSDLLex_IN;
 YY_BSDLLex_OFILE *YY_BSDLLex_OUT;
 YY_BSDLLex_LEX_RETURN YY_BSDLLex_LEX ( YY_BSDLLex_LEX_PARAM);
 YY_BSDLLex_CLASS(YY_BSDLLex_CONSTRUCTOR_PARAM) ;
 virtual ~YY_BSDLLex_CLASS() ;
#if YY_BSDLLex_DEBUG != 0
 int YY_BSDLLex_DEBUG_FLAG;
#endif
 public: /* added members */
 YY_BSDLLex_MEMBERS 
};
#endif



/* declaration of externs for public use of yylex scanner */

/* % here is the declaration from section2 %header{ */ 
#line 156 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/component/src/BSDLLex.l"
#endif
#line 375 "/usr/local/lib/flexskel.h"

/* end of generated header */
