/*
 * $RCSfile: PSWriter3D.C,v $
 *
 * Copyright (C) 1994-96, Stephan Amann <amann@iam.unibe.ch>
 *                        Christoph Streit <streit@iam.unibe.ch>
 *                        University of Berne, Switzerland
 *
 * All rights reserved.
 *
 * This software may be freely copied, modified, and redistributed
 * provided that this copyright notice is preserved on all copies.
 *
 * You may not distribute this software, in whole or in part, as part of
 * any commercial product without the express consent of the authors.
 *
 * There is no warranty or other guarantee of fitness of this software
 * for any purpose.  It is provided solely "as is".
 *
 * -----------------------------------------------------------------------------
 *  $Id: PSWriter3D.C,v 1.3 1996/08/01 12:00:58 streit Exp $
 * -----------------------------------------------------------------------------
 */
 

#include "booga/object/Camera3D.h"
#include "booga/component/Wireframe.h"
#include "booga/component/PSWriter2D.h"
#include "booga/component/PSWriter3D.h"

//___________________________________________________________________ PSWriter3D

implementRTTI(PSWriter3D, Operation3D);

PSWriter3D::PSWriter3D(const RCString& filename)
: myFilename(filename)
{
  myCamera = NULL;
  myHasAdoptedCamera = false;
}

void PSWriter3D::adoptCamera(Camera3D* camera)
{
  if (camera == NULL) {
    Report::warning("[PSWriter3D::adoptCamera] NULL pointer passed");
    return;
  }
    
  if (myCamera != NULL && myCamera != camera)
    delete myCamera;

  myCamera = camera; 
  myHasAdoptedCamera = true;
}

void PSWriter3D::deleteCamera()
{
  if (myCamera != NULL) {
    delete myCamera;
    myCamera = NULL;
  }
  myHasAdoptedCamera = false;
}

bool PSWriter3D::doExecute()
{
  //
  // Create 2D view of the scene by applying a wireframe renderer.
  //
  Wireframe wireframe;
  if (myCamera != NULL)
    wireframe.adoptCamera((Camera3D*)myCamera->copy());
  
  World2D* world2D = wireframe.execute(getWorld());

  //
  // Postscript output generated by PSWriter2D component.
  //    
  PSWriter2D writer(myFilename);
  writer.execute(world2D);
   
  delete world2D;
  
  return !(wireframe.hasFailed() || writer.hasFailed());
}

