#ifndef FLEX_HEADER_VRMLLex_h
#define FLEX_HEADER_VRMLLex_h
#line 30 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/component/src/VRMLLex.l"
#include "VRMLYacc.h"
#define YY_VRMLLex_CHAR char
#line 1 "/usr/local/lib/flexskel.h"
/* A lexical scanner header generated by flex */
/* MODIFIED FOR C++ CLASS BY Alain Coetmeur: coetmeur(at)icdc.fr */
/* Note that (at) mean the 'at' symbol that I cannot write */
/* because it is expanded to the class name */
/* made at Informatique-CDC, Research&development department */
/* company from the Caisse Des Depots et Consignations */


/*********************************************/
/* SYSTEM dependent declaration, includes... */
/*********************************************/
/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif
#ifdef __cplusplus
#ifndef YY_USE_PROTOS
#define YY_USE_PROTOS
#endif
#ifndef YY_USE_CLASS
#define YY_USE_CLASS
#endif
#else	/* ! __cplusplus */
#ifdef __STDC__
#ifdef __GNUC__
#else
#endif	/* __GNUC__ */
#ifndef YY_USE_PROTOS
#define YY_USE_PROTOS
#endif
#endif	/* __STDC__ */
#endif	/* ! __cplusplus */
/*********************************************/
/* COMPILER DEPENDENT   MACROS               */
/*********************************************/
/* use prototypes in function declarations */
#ifndef YY_PROTO
#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif
#endif
#include <stdio.h>




/* % here is the declaration from section1 %header{  */ 
#line 40 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/component/src/VRMLLex.l"
#define YY_VRMLLex_DEBUG  1
#line 41 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/component/src/VRMLLex.l"
#define YY_VRMLLex_DEBUG_FLAG  myScannerDebugFlag
#line 42 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/component/src/VRMLLex.l"
#define YY_VRMLLex_DEBUG_INIT  0
#line 44 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/component/src/VRMLLex.l"
#define YY_VRMLLex_CONSTRUCTOR_PARAM  void
#line 45 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/component/src/VRMLLex.l"
#define YY_VRMLLex_CONSTRUCTOR_INIT  : myCurrentLine(1)
#line 46 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/component/src/VRMLLex.l"
#define YY_VRMLLex_CONSTRUCTOR_CODE  
#line 48 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/component/src/VRMLLex.l"
#define YY_VRMLLex_IN  inputFile
#line 50 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/component/src/VRMLLex.l"
#define YY_VRMLLex_MEMBERS                                               \
  public:                                                    \
     const char* getCurrentToken() const { return yytext; }  \
     int getCurrentLine() const { return myCurrentLine; }    \
     const RCString& getCurrentFilename() const              \
     { return myCurrentFilename; }                           \
  private:                                                   \
     int myLineNo;                                           \
     int myCurrentLine;                                      \
     RCString myCurrentFilename;
#line 61 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/component/src/VRMLLex.l"
#define YY_VRMLLex_LEX  scan
#line 62 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/component/src/VRMLLex.l"
#define YY_VRMLLex_LEX_PARAM  YY_VRMLYacc_STYPE& yylval
#line 83 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/component/src/VRMLLex.l"
#line 52 "/usr/local/lib/flexskel.h"

#ifdef YY_USE_CLASS
#ifdef YY_VRMLLex_IOSTREAM
#include <iostream.h>
#define YY_VRMLLex_IFILE  istream
#define YY_VRMLLex_OFILE ostream 
#define YY_VRMLLex_ERRFILE cerr

#ifndef YY_VRMLLex_IFILE_DEFAULT
#define YY_VRMLLex_IFILE_DEFAULT &cin
#endif

#ifndef YY_VRMLLex_OFILE_DEFAULT
#define YY_VRMLLex_OFILE_DEFAULT &cout
#endif

#endif
#endif

#ifndef YY_VRMLLex_IFILE
#define YY_VRMLLex_IFILE FILE 
#endif

#ifndef YY_VRMLLex_OFILE
#define YY_VRMLLex_OFILE FILE 
#endif

#ifndef YY_VRMLLex_ERRFILE
#define YY_VRMLLex_ERRFILE stderr
#endif

#ifndef YY_VRMLLex_IFILE_DEFAULT
#define YY_VRMLLex_IFILE_DEFAULT stdin
#endif

#ifndef YY_VRMLLex_OFILE_DEFAULT
#define YY_VRMLLex_OFILE_DEFAULT stdout
#endif




#ifndef YY_VRMLLex_TEXT
#define YY_VRMLLex_TEXT yytext
#endif
#ifndef YY_VRMLLex_LENG
#define YY_VRMLLex_LENG yyleng
#endif
#ifndef YY_VRMLLex_IN
#define YY_VRMLLex_IN yyin
#endif
#ifndef YY_VRMLLex_OUT
#define YY_VRMLLex_OUT yyout
#endif

#ifndef YY_VRMLLex_LEX_RETURN
#define YY_VRMLLex_LEX_RETURN int
#else
#ifndef YY_VRMLLex_LEX_DEFINED
#define YY_VRMLLex_LEX_DEFINED 
#endif
#endif

#ifndef YY_VRMLLex_LEX
#define YY_VRMLLex_LEX yylex
#else
#ifndef YY_VRMLLex_LEX_DEFINED
#define YY_VRMLLex_LEX_DEFINED 
#endif
#endif

#ifndef YY_VRMLLex_LEX_PARAM
#ifndef YY_USE_PROTOS
#define YY_VRMLLex_LEX_PARAM 
#else
#define YY_VRMLLex_LEX_PARAM void
#endif
#else
#ifndef YY_VRMLLex_LEX_DEFINED
#define YY_VRMLLex_LEX_DEFINED 
#endif
#endif

#ifndef YY_VRMLLex_LEX_PARAM_DEF
#define YY_VRMLLex_LEX_PARAM_DEF
#else
#ifndef YY_VRMLLex_LEX_DEFINED
#define YY_VRMLLex_LEX_DEFINED 
#endif
#endif

#ifndef YY_VRMLLex_RESTART
#define YY_VRMLLex_RESTART yyrestart
#endif
#ifndef YY_VRMLLex_SWITCH_TO_BUFFER
#define YY_VRMLLex_SWITCH_TO_BUFFER yy_switch_to_buffer
#endif
#ifndef YY_VRMLLex_LOAD_BUFFER_STATE
#define YY_VRMLLex_LOAD_BUFFER_STATE yy_load_buffer_state
#endif

#ifndef YY_VRMLLex_CREATE_BUFFER
#define YY_VRMLLex_CREATE_BUFFER yy_create_buffer
#ifndef YY_USE_CLASS
#ifndef yy_new_buffer
#define yy_new_buffer yy_create_buffer
#endif
#endif
#endif
#ifndef YY_VRMLLex_DELETE_BUFFER
#define YY_VRMLLex_DELETE_BUFFER yy_delete_buffer
#endif
#ifndef YY_VRMLLex_INIT_BUFFER
#define YY_VRMLLex_INIT_BUFFER yy_init_buffer
#endif



#ifdef YY_VRMLLex_FLEX_DEBUG
#ifndef YY_VRMLLex_DEBUG
#define YY_VRMLLex_DEBUG 1
#endif
#else
#ifndef YY_VRMLLex_DEBUG
#define YY_VRMLLex_DEBUG 0
#endif
#endif

#if YY_VRMLLex_DEBUG != 0
#ifndef YY_VRMLLex_DEBUG_FLAG
#define YY_VRMLLex_DEBUG_FLAG yy_flex_debug
#endif
#ifndef YY_VRMLLex_DEBUG_INIT
#define YY_VRMLLex_DEBUG_INIT 1
#endif
#endif




#ifndef YY_USE_CLASS
#ifndef YY_VRMLLex_CURRENT_BUFFER
#define YY_VRMLLex_CURRENT_BUFFER yy_current_buffer
#endif
typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern void YY_VRMLLex_RESTART YY_PROTO(( YY_VRMLLex_IFILE *input_file ));
extern void YY_VRMLLex_SWITCH_TO_BUFFER YY_PROTO(( YY_BUFFER_STATE new_buffer ));
extern void YY_VRMLLex_LOAD_BUFFER_STATE YY_PROTO(( void ));
extern YY_BUFFER_STATE YY_VRMLLex_CREATE_BUFFER YY_PROTO(( YY_VRMLLex_IFILE *file, int size ));
extern void YY_VRMLLex_DELETE_BUFFER YY_PROTO(( YY_BUFFER_STATE b ));
extern void YY_VRMLLex_INIT_BUFFER YY_PROTO(( YY_BUFFER_STATE b, YY_VRMLLex_IFILE *file ));

#if YY_VRMLLex_DEBUG != 0
extern int YY_VRMLLex_DEBUG_FLAG ;
#endif
extern YY_VRMLLex_CHAR  *YY_VRMLLex_TEXT;
extern int YY_VRMLLex_LENG;
extern YY_VRMLLex_IFILE *YY_VRMLLex_IN;
extern YY_VRMLLex_OFILE *YY_VRMLLex_OUT;
#ifdef YY_VRMLLex_LEX_DEFINED
extern YY_VRMLLex_LEX_RETURN YY_VRMLLex_LEX ( YY_VRMLLex_LEX_PARAM )
YY_VRMLLex_LEX_PARAM_DEF
#else
#ifndef YY_DECL
extern YY_VRMLLex_LEX_RETURN YY_VRMLLex_LEX ( YY_VRMLLex_LEX_PARAM )
YY_VRMLLex_LEX_PARAM_DEF
#else
/* no declaration if oldstyle flex */
#endif
#endif
#else

#ifndef YY_VRMLLex_CURRENT_BUFFER
#define YY_VRMLLex_CURRENT_BUFFER YY_CURRENT_BUFFER
#endif
#ifndef YY_VRMLLex_CLASS
#define YY_VRMLLex_CLASS VRMLLex
#endif
#ifndef YY_VRMLLex_ECHO
#define YY_VRMLLex_ECHO yy_echo
#endif
#ifdef YY_VRMLLex_ECHO_PURE
#define YY_VRMLLex_ECHO_NOCODE
#endif

#ifndef YY_VRMLLex_ECHO_CODE
#ifndef YY_VRMLLex_IOSTREAM
#define YY_VRMLLex_ECHO_CODE fwrite( (char *) YY_VRMLLex_TEXT, YY_VRMLLex_LENG, 1, YY_VRMLLex_OUT );
#else
#define YY_VRMLLex_ECHO_CODE (YY_VRMLLex_OUT->write( (char *) YY_VRMLLex_TEXT, YY_VRMLLex_LENG));
#endif
#endif

#ifndef YY_VRMLLex_INPUT
#define YY_VRMLLex_INPUT yy_input
#endif
#ifdef YY_VRMLLex_INPUT_PURE
#define YY_VRMLLex_INPUT_NOCODE
#endif

#ifndef YY_VRMLLex_INPUT_CODE
#ifndef YY_VRMLLex_IOSTREAM
#define YY_VRMLLex_INPUT_CODE return result= fread(  buffer, 1,max_size,YY_VRMLLex_IN );
#else
#define YY_VRMLLex_INPUT_CODE if(YY_VRMLLex_IN->eof())  result=0;else {YY_VRMLLex_IN->read(buffer,max_size);result=YY_VRMLLex_IN->gcount();YY_VRMLLex_IN->clear(YY_VRMLLex_IN->rdstate()&(~ios::failbit));if(YY_VRMLLex_IN->bad()) result= -1;} return result;
#endif
#endif

#ifdef YY_VRMLLex_FATAL_ERROR_PURE
#define YY_VRMLLex_FATAL_ERRO_NOCODE
#endif
#ifndef YY_VRMLLex_FATAL_ERROR
#define YY_VRMLLex_FATAL_ERROR yy_fatal_error
#endif

#ifndef YY_VRMLLex_FATAL_ERROR_CODE
#ifndef YY_VRMLLex_IOSTREAM
#define YY_VRMLLex_FATAL_ERROR_CODE fputs( msg, YY_VRMLLex_ERRFILE );putc( '\n', YY_VRMLLex_ERRFILE );exit( 1 );
#else
#define YY_VRMLLex_FATAL_ERROR_CODE YY_VRMLLex_ERRFILE<< msg <<endl;exit( 1 );
#endif
#endif

#ifndef YY_VRMLLex_WRAP
#define YY_VRMLLex_WRAP yy_wrap
#endif
#ifdef YY_VRMLLex_WRAP_PURE
#define YY_VRMLLex_WRAP_NOCODE
#endif
#ifndef YY_VRMLLex_WRAP_CODE
#define YY_VRMLLex_WRAP_CODE return 1;
#endif


#ifndef YY_VRMLLex_INHERIT
#define YY_VRMLLex_INHERIT
#endif
#ifndef YY_VRMLLex_MEMBERS
#define YY_VRMLLex_MEMBERS 
#endif
#ifndef YY_VRMLLex_CONSTRUCTOR_PARAM
#define YY_VRMLLex_CONSTRUCTOR_PARAM
#endif
#ifndef YY_VRMLLex_CONSTRUCTOR_CODE
#define YY_VRMLLex_CONSTRUCTOR_CODE
#endif
#ifndef YY_VRMLLex_CONSTRUCTOR_INIT
#define YY_VRMLLex_CONSTRUCTOR_INIT
#endif
#ifndef YY_VRMLLex_DESTRUCTOR_CODE
#define YY_VRMLLex_DESTRUCTOR_CODE
#endif
typedef struct yy_buffer_state *YY_BUFFER_STATE;

class YY_VRMLLex_CLASS YY_VRMLLex_INHERIT
{
 private:/* data */
 YY_VRMLLex_CHAR  *yy_c_buf_p;
 YY_VRMLLex_CHAR  yy_hold_char;
 int yy_n_chars;
 int yy_init;
 int yy_start;
 int yy_did_buffer_switch_on_eof;
 private: /* functions */
 void yy_initialize();
 int input();
 int yyinput() {return input();};
 int yy_get_next_buffer();
 void yyunput( YY_VRMLLex_CHAR  c, YY_VRMLLex_CHAR  *buf_ptr );
 /* use long instead of yy_state_type because it is undef */
 long yy_get_previous_state_ ( void );
 long yy_try_NUL_trans_  ( long current_state_ );
 protected:/* non virtual */
 YY_BUFFER_STATE YY_VRMLLex_CURRENT_BUFFER;
 void YY_VRMLLex_RESTART ( YY_VRMLLex_IFILE *input_file );
 void YY_VRMLLex_SWITCH_TO_BUFFER( YY_BUFFER_STATE new_buffer );
 void YY_VRMLLex_LOAD_BUFFER_STATE( void );
 YY_BUFFER_STATE YY_VRMLLex_CREATE_BUFFER( YY_VRMLLex_IFILE *file, int size );
 void YY_VRMLLex_DELETE_BUFFER( YY_BUFFER_STATE b );
 void YY_VRMLLex_INIT_BUFFER( YY_BUFFER_STATE b, YY_VRMLLex_IFILE *file );
 protected: /* virtual */
 virtual void YY_VRMLLex_ECHO()
#ifdef YY_VRMLLex_ECHO_PURE
  =0
#endif
  ;
 virtual int  YY_VRMLLex_INPUT(char  *buf,int &result,int max_size)
#ifdef YY_VRMLLex_INPUT_PURE
  =0
#endif
  ;
 virtual void  YY_VRMLLex_FATAL_ERROR(char *msg)
#ifdef YY_VRMLLex_FATAL_ERROR_PURE
  =0
#endif
  ;
 virtual int  YY_VRMLLex_WRAP()
#ifdef YY_VRMLLex_WRAP_PURE
  =0
#endif
  ;
 public:
 YY_VRMLLex_CHAR  *YY_VRMLLex_TEXT;
 int YY_VRMLLex_LENG;
 YY_VRMLLex_IFILE *YY_VRMLLex_IN;
 YY_VRMLLex_OFILE *YY_VRMLLex_OUT;
 YY_VRMLLex_LEX_RETURN YY_VRMLLex_LEX ( YY_VRMLLex_LEX_PARAM);
 YY_VRMLLex_CLASS(YY_VRMLLex_CONSTRUCTOR_PARAM) ;
 virtual ~YY_VRMLLex_CLASS() ;
#if YY_VRMLLex_DEBUG != 0
 int YY_VRMLLex_DEBUG_FLAG;
#endif
 public: /* added members */
 YY_VRMLLex_MEMBERS 
};
#endif



/* declaration of externs for public use of yylex scanner */

/* % here is the declaration from section2 %header{ */ 
#line 339 "/home/fcg/BOOGA/workspaces/core-dev/shared_src/framework/component/src/VRMLLex.l"
#endif
#line 375 "/usr/local/lib/flexskel.h"

/* end of generated header */
