#ifndef GL_EXT_H
#define GL_EXT_H

	/*
	 * 1.0 Extensions
	 */
        /* GL_EXT_blend_minmax and GL_EXT_blend_color */
/*
#define	GL_CONSTANT_COLOR_EXT		 0x8001
#define	GL_ONE_MINUS_CONSTANT_COLOR_EXT	 0x8002
#define	GL_CONSTANT_ALPHA_EXT		 0x8003
#define	GL_ONE_MINUS_CONSTANT_ALPHA_EXT	 0x8004
#define	GL_BLEND_EQUATION_EXT		 0x8009
#define	GL_MIN_EXT			 0x8007
#define	GL_MAX_EXT			 0x8008
#define	GL_FUNC_ADD_EXT			 0x8006
#define	GL_FUNC_SUBTRACT_EXT		 0x800A
#define	GL_FUNC_REVERSE_SUBTRACT_EXT	 0x800B
#define	GL_BLEND_COLOR_EXT		 0x8005
*/
	/* GL_EXT_polygon_offset */
/*
#define        GL_POLYGON_OFFSET_EXT            0x8037
#define        GL_POLYGON_OFFSET_FACTOR_EXT     0x8038
#define        GL_POLYGON_OFFSET_BIAS_EXT       0x8039
*/
	/* GL_EXT_vertex_array */
/*
#define	GL_VERTEX_ARRAY_EXT			 0x8074
#define	GL_NORMAL_ARRAY_EXT			 0x8075
#define	GL_COLOR_ARRAY_EXT			 0x8076
#define	GL_INDEX_ARRAY_EXT			 0x8077
#define	GL_TEXTURE_COORD_ARRAY_EXT		 0x8078
#define	GL_EDGE_FLAG_ARRAY_EXT			 0x8079
#define	GL_VERTEX_ARRAY_SIZE_EXT		 0x807A
#define	GL_VERTEX_ARRAY_TYPE_EXT		 0x807B
#define	GL_VERTEX_ARRAY_STRIDE_EXT		 0x807C
#define	GL_VERTEX_ARRAY_COUNT_EXT		 0x807D
#define	GL_NORMAL_ARRAY_TYPE_EXT		 0x807E
#define	GL_NORMAL_ARRAY_STRIDE_EXT		 0x807F
#define	GL_NORMAL_ARRAY_COUNT_EXT		 0x8080
#define	GL_COLOR_ARRAY_SIZE_EXT			 0x8081
#define	GL_COLOR_ARRAY_TYPE_EXT			 0x8082
#define	GL_COLOR_ARRAY_STRIDE_EXT		 0x8083
#define	GL_COLOR_ARRAY_COUNT_EXT		 0x8084
#define	GL_INDEX_ARRAY_TYPE_EXT			 0x8085
#define	GL_INDEX_ARRAY_STRIDE_EXT		 0x8086
#define	GL_INDEX_ARRAY_COUNT_EXT		 0x8087
#define	GL_TEXTURE_COORD_ARRAY_SIZE_EXT		 0x8088
#define	GL_TEXTURE_COORD_ARRAY_TYPE_EXT		 0x8089
#define	GL_TEXTURE_COORD_ARRAY_STRIDE_EXT	 0x808A
#define	GL_TEXTURE_COORD_ARRAY_COUNT_EXT	 0x808B
#define	GL_EDGE_FLAG_ARRAY_STRIDE_EXT		 0x808C
#define	GL_EDGE_FLAG_ARRAY_COUNT_EXT		 0x808D
#define	GL_VERTEX_ARRAY_POINTER_EXT		 0x808E
#define	GL_NORMAL_ARRAY_POINTER_EXT		 0x808F
#define	GL_COLOR_ARRAY_POINTER_EXT		 0x8090
#define	GL_INDEX_ARRAY_POINTER_EXT		 0x8091
#define	GL_TEXTURE_COORD_ARRAY_POINTER_EXT	 0x8092
#define	GL_EDGE_FLAG_ARRAY_POINTER_EXT		 0x8093
*/
	/* GL_EXT_texture_object */
/*
#define	GL_TEXTURE_PRIORITY_EXT		 0x8066
#define	GL_TEXTURE_RESIDENT_EXT		 0x8067
#define	GL_TEXTURE_1D_BINDING_EXT	 0x8068
#define	GL_TEXTURE_2D_BINDING_EXT	 0x8069
*/
	/* GL_EXT_texture3D */
/*
#define	GL_PACK_SKIP_IMAGES_EXT		 0x806B
#define	GL_PACK_IMAGE_HEIGHT_EXT	 0x806C
#define	GL_UNPACK_SKIP_IMAGES_EXT	 0x806D
#define	GL_UNPACK_IMAGE_HEIGHT_EXT	 0x806E
#define	GL_TEXTURE_3D_EXT		 0x806F
#define	GL_PROXY_TEXTURE_3D_EXT		 0x8070
#define	GL_TEXTURE_DEPTH_EXT		 0x8071
#define	GL_TEXTURE_WRAP_R_EXT		 0x8072
#define	GL_MAX_3D_TEXTURE_SIZE_EXT	 0x8073
#define	GL_TEXTURE_3D_BINDING_EXT	 0x806A
*/
        /* GL_EXT_paletted_texture */


#define	GL_TABLE_TOO_LARGE_EXT			 0x8031
#define	GL_COLOR_TABLE_FORMAT_EXT		 0x80D8
#define	GL_COLOR_TABLE_WIDTH_EXT		 0x80D9
#define	GL_COLOR_TABLE_RED_SIZE_EXT		 0x80DA
#define	GL_COLOR_TABLE_GREEN_SIZE_EXT		 0x80DB
#define	GL_COLOR_TABLE_BLUE_SIZE_EXT		 0x80DC
#define	GL_COLOR_TABLE_ALPHA_SIZE_EXT	 	 0x80DD
#define	GL_COLOR_TABLE_LUMINANCE_SIZE_EXT	 0x80DE
#define	GL_COLOR_TABLE_INTENSITY_SIZE_EXT	 0x80DF
#define	GL_TEXTURE_INDEX_SIZE_EXT		 0x80E1 /*XXX right value??*/
#define	GL_COLOR_INDEX1_EXT			 0x80E2
#define	GL_COLOR_INDEX2_EXT			 0x80E3
#define	GL_COLOR_INDEX4_EXT			 0x80E4
#define	GL_COLOR_INDEX8_EXT			 0x80E5
#define	GL_COLOR_INDEX12_EXT			 0x80E6
#define	GL_COLOR_INDEX16_EXT			 0x80E7

	/* GL_EXT_shared_texture_palette */
#define	GL_SHARED_TEXTURE_PALETTE_EXT		 0x81FB
#define	GL_POINT_SIZE_MIN_EXT			 0x8126
#define	GL_POINT_SIZE_MAX_EXT			 0x8127
#define	GL_POINT_FADE_THRESHOLD_SIZE_EXT	 0x8128
#define	GL_DISTANCE_ATTENUATION_EXT		 0x8129

#endif
