/*
 * $RCSfile: PreorderTraversal3D.h,v $
 *
 * Copyright (C) 1994-96, Christoph Streit <streit@iam.unibe.ch>
 *                        Stephan Amann <amann@iam.unibe.ch>
 *                        University of Berne, Switzerland
 *
 * All rights reserved.
 *
 * This software may be freely copied, modified, and redistributed
 * provided that this copyright notice is preserved on all copies.
 *
 * You may not distribute this software, in whole or in part, as part of
 * any commercial product without the express consent of the authors.
 *
 * There is no warranty or other guarantee of fitness of this software
 * for any purpose.  It is provided solely as is.
 *
 * -----------------------------------------------------------------------------
 *  $Id: PreorderTraversal3D.h,v 1.1 1996/09/13 08:05:54 streit Exp $
 * -----------------------------------------------------------------------------
 */
   
#ifndef _PreorderTraversal3D_H
#define _PreorderTraversal3D_H

#include "booga/component/AbstractTraversal3D.h"

//__________________________________________________________ PreorderTraversal3D

class PreorderTraversal3D : public AbstractTraversal3D {
declareRTTI(PreorderTraversal3D);
// enable RTTI support

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// Constructors, destructors, assignment
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
public:
  // PreorderTraversal3D();            // Use default version.               
  // PreorderTraversal3D(const PreorderTraversal3D&);            
  // Use default version.

public:
  //  virtual ~PreorderTraversal3D();  // Use deafult version.                        
  
public:
  // PreorderTraversal3D& operator=(const PreorderTraversal3D&); 
  // Use default version.
  
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// New methods of class PreorderTraversal3D
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
private:
  bool doTraverse(Object3D* obj);
  // Recursively traverses the object structure. Calls traverse() for each 
  // object found or generated by a calling decomposition() on a unknown 
  // object
  // Returns true : continue
  //         false: abort the traversal

  void beforeVisitObject(Object3D *object);
  void afterVisitObject(Object3D* object);
  
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// From class MTraversal<>
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
protected:
  virtual bool traverse(Object3D* obj);
  // Calls doTraverse()
};

#endif // _PreorderTraversal3D_H
