/*
 * $RCSfile: GLTraversal2D.h,v $
 *
 * Traversal logic for GL rasterizer. Performs a preorder traversal of the
 * world and applies textures and object transformations to the GL engine.
 *
 * Copyright (C) 1994-96, Christoph Streit <streit@iam.unibe.ch>
 *                        Stephan Amann <amann@iam.unibe.ch>
 *                        University of Berne, Switzerland
 *
 * All rights reserved.
 *
 * This software may be freely copied, modified, and redistributed
 * provided that this copyright notice is preserved on all copies.
 *
 * You may not distribute this software, in whole or in part, as part of
 * any commercial product without the express consent of the authors.
 *
 * There is no warranty or other guarantee of fitness of this software
 * for any purpose.  It is provided solely as is.
 *
 * -----------------------------------------------------------------------------
 *  $Id: GLTraversal2D.h,v 1.3 1996/08/09 14:14:21 streit Exp $
 * -----------------------------------------------------------------------------
 */
   
#ifndef _GLTraversal2D_H
#define _GLTraversal2D_H

#include "booga/object/Texture2DContext.h"
#include "booga/glwrapper/GLAbstractTraversal2D.h"

//________________________________________________________________ GLTraversal2D

class GLTraversal2D : public GLAbstractTraversal2D {
declareRTTI(GLTraversal2D);
// enable RTTI support

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// Constructors, destructors, assignment
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
public:
  // GLTraversal2D();                                // Use default version.
  // GLTraversal2D(const GLTraversal2D&);            // Use default version.

public:
  // virtual ~GLTraversal2D();                       // Use default version.      

public:
  // GLTraversal2D& operator=(const GLTraversal2D&); // Use default version.

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// New methods of class GLTraversal2D
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
private:
  bool doTraverse(Object2D* obj);
  // Recursively traverses the object structure. Calls traverse() for each 
  // object found or generated by a calling decomposition() on a unknown 
  // object
  // Returns true : continue
  //         false: abort the traversal

  void beforeVisitObject(Object2D *object);
  void afterVisitObject(Object2D* object);
  
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// From class MTraversal<>
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
protected:
  virtual bool traverse(Object2D* obj);
  // Calls doTraverse()

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// My data members
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
private:
  Texture2DContext myTextureContext;
};

//______________________________________________________________________ INLINES


#endif // _GLTraversal2D_H
